import { defineStore } from "pinia";

export const shopStore = defineStore("alerts", {
  state: () => {
    return {
      search: "",
      shortNav: [
        "intel i3 10е поколение",
        "geforce3050ti",
        "процессор",
        "оперативная память",
        "заправка картридж",
        "видеокарта",
        "мониторы",
        "canon mf3010",
        "epson принтеры",
        "ремонт компьютеров",
        "ssd nvme 512gb",
      ],
      arr: [
        { img: "/src/assets/img/magazin/Group2.png", link: "/" },
        { img: "/src/assets/img/magazin/Group2.png", link: "/" },
        { img: "/src/assets/img/magazin/Group2.png", link: "/" },
        { img: "/src/assets/img/magazin/Group2.png", link: "/" },
        { img: "/src/assets/img/magazin/Group2.png", link: "/" },
        { img: "/src/assets/img/magazin/Group2.png", link: "/" },
      ],
      cardSwiper: [
        [
          "Компьютерные комплектующие",
          [
            {
              name: "RAM 8gb 3200hz для ПК от HYPERX с радиато",
              link: "/",
              img: 1,
              rating: 4.95,
              sale: 0,
              xit: true,
              review: 31,
              typeOfMoney: "В наличии",
              cost: "1500000",
              currency: "сум",
            },
            {
              name: "RAM 8gb 3200hz для ПК от HYPERX с радиато",
              link: "/",
              img: 2,
              rating: 4.95,
              sale: 0,
              xit: true,
              review: 31,
              typeOfMoney: "В наличии",
              cost: "1500000",
              currency: "сум",
            },
            {
              name: "RAM 8gb 3200hz для ПК от HYPERX с радиато",
              link: "/",
              img: 3,
              rating: 4.95,
              sale: 0,
              xit: true,
              review: 31,
              typeOfMoney: "В наличии",
              cost: "1500000",
              currency: "сум",
            },
            {
              name: "RAM 8gb 3200hz для ПК от HYPERX с радиато",
              link: "/",
              img: 1,
              rating: 4.95,
              sale: 0,
              xit: true,
              review: 31,
              typeOfMoney: "В наличии",
              cost: "1500000",
              currency: "сум",
            },
            {
              name: "RAM 8gb 3200hz для ПК от HYPERX с радиато",
              link: "/",
              img: 2,
              rating: 4.95,
              sale: 0,
              xit: true,
              review: 31,
              typeOfMoney: "В наличии",
              cost: "1500000",
              currency: "сум",
            },
            {
              name: "RAM 8gb 3200hz для ПК от HYPERX с радиато",
              link: "/",
              img: 3,
              rating: 4.95,
              sale: 0,
              xit: true,
              review: 31,
              typeOfMoney: "В наличии",
              cost: "1500000",
              currency: "сум",
            },
            {
              name: "RAM 8gb 3200hz для ПК от HYPERX с радиато",
              link: "/",
              img: 1,
              rating: 4.95,
              sale: 0,
              xit: true,
              review: 31,
              typeOfMoney: "В наличии",
              cost: "1500000",
              currency: "сум",
            },
            {
              name: "RAM 8gb 3200hz для ПК от HYPERX с радиато",
              link: "/",
              img: 2,
              rating: 4.95,
              sale: 0,
              xit: true,
              review: 31,
              typeOfMoney: "В наличии",
              cost: "1500000",
              currency: "сум",
            },
            {
              name: "RAM 8gb 3200hz для ПК от HYPERX с радиато",
              link: "/",
              img: 3,
              rating: 4.95,
              sale: 0,
              xit: true,
              review: 31,
              typeOfMoney: "В наличии",
              cost: "1500000",
              currency: "сум",
            },
          ],
        ],
        [
          "Принтеры",
          [
            {
              name: "RAM 8gb 3200hz для ПК от HYPERX с радиато",
              link: "/",
              img: 1,
              rating: 4.95,
              sale: 0,
              xit: true,
              review: 31,
              typeOfMoney: "В наличии",
              cost: "1500000",
              currency: "сум",
            },
            {
              name: "RAM 8gb 3200hz для ПК от HYPERX с радиато",
              link: "/",
              img: 2,
              rating: 4.95,
              sale: 0,
              xit: true,
              review: 31,
              typeOfMoney: "В наличии",
              cost: "1500000",
              currency: "сум",
            },
            {
              name: "RAM 8gb 3200hz для ПК от HYPERX с радиато",
              link: "/",
              img: 3,
              rating: 4.95,
              sale: 0,
              xit: true,
              review: 31,
              typeOfMoney: "В наличии",
              cost: "1500000",
              currency: "сум",
            },
            {
              name: "RAM 8gb 3200hz для ПК от HYPERX с радиато",
              link: "/",
              img: 1,
              rating: 4.95,
              sale: 0,
              xit: true,
              review: 31,
              typeOfMoney: "В наличии",
              cost: "1500000",
              currency: "сум",
            },
            {
              name: "RAM 8gb 3200hz для ПК от HYPERX с радиато",
              link: "/",
              img: 2,
              rating: 4.95,
              sale: 0,
              xit: true,
              review: 31,
              typeOfMoney: "В наличии",
              cost: "1500000",
              currency: "сум",
            },
            {
              name: "RAM 8gb 3200hz для ПК от HYPERX с радиато",
              link: "/",
              img: 3,
              rating: 4.95,
              sale: 0,
              xit: true,
              review: 31,
              typeOfMoney: "В наличии",
              cost: "1500000",
              currency: "сум",
            },
            {
              name: "RAM 8gb 3200hz для ПК от HYPERX с радиато",
              link: "/",
              img: 1,
              rating: 4.95,
              sale: 0,
              xit: true,
              review: 31,
              typeOfMoney: "В наличии",
              cost: "1500000",
              currency: "сум",
            },
            {
              name: "RAM 8gb 3200hz для ПК от HYPERX с радиато",
              link: "/",
              img: 2,
              rating: 4.95,
              sale: 0,
              xit: true,
              review: 31,
              typeOfMoney: "В наличии",
              cost: "1500000",
              currency: "сум",
            },
            {
              name: "RAM 8gb 3200hz для ПК от HYPERX с радиато",
              link: "/",
              img: 3,
              rating: 4.95,
              sale: 0,
              xit: true,
              review: 31,
              typeOfMoney: "В наличии",
              cost: "1500000",
              currency: "сум",
            },
          ],
        ],
        [
          "Умный дом",
          [
            {
              name: "RAM 8gb 3200hz для ПК от HYPERX с радиато",
              link: "/",
              img: 1,
              rating: 4.95,
              sale: 0,
              xit: true,
              review: 31,
              typeOfMoney: "В наличии",
              cost: "1500000",
              currency: "сум",
            },
            {
              name: "RAM 8gb 3200hz для ПК от HYPERX с радиато",
              link: "/",
              img: 2,
              rating: 4.95,
              sale: 0,
              xit: true,
              review: 31,
              typeOfMoney: "В наличии",
              cost: "1500000",
              currency: "сум",
            },
            {
              name: "RAM 8gb 3200hz для ПК от HYPERX с радиато",
              link: "/",
              img: 3,
              rating: 4.95,
              sale: 0,
              xit: true,
              review: 31,
              typeOfMoney: "В наличии",
              cost: "1500000",
              currency: "сум",
            },
            {
              name: "RAM 8gb 3200hz для ПК от HYPERX с радиато",
              link: "/",
              img: 1,
              rating: 4.95,
              sale: 0,
              xit: true,
              review: 31,
              typeOfMoney: "В наличии",
              cost: "1500000",
              currency: "сум",
            },
            {
              name: "RAM 8gb 3200hz для ПК от HYPERX с радиато",
              link: "/",
              img: 2,
              rating: 4.95,
              sale: 0,
              xit: true,
              review: 31,
              typeOfMoney: "В наличии",
              cost: "1500000",
              currency: "сум",
            },
            {
              name: "RAM 8gb 3200hz для ПК от HYPERX с радиато",
              link: "/",
              img: 3,
              rating: 4.95,
              sale: 0,
              xit: true,
              review: 31,
              typeOfMoney: "В наличии",
              cost: "1500000",
              currency: "сум",
            },
            {
              name: "RAM 8gb 3200hz для ПК от HYPERX с радиато",
              link: "/",
              img: 1,
              rating: 4.95,
              sale: 0,
              xit: true,
              review: 31,
              typeOfMoney: "В наличии",
              cost: "1500000",
              currency: "сум",
            },
            {
              name: "RAM 8gb 3200hz для ПК от HYPERX с радиато",
              link: "/",
              img: 2,
              rating: 4.95,
              sale: 0,
              xit: true,
              review: 31,
              typeOfMoney: "В наличии",
              cost: "1500000",
              currency: "сум",
            },
            {
              name: "RAM 8gb 3200hz для ПК от HYPERX с радиато",
              link: "/",
              img: 3,
              rating: 4.95,
              sale: 0,
              xit: true,
              review: 31,
              typeOfMoney: "В наличии",
              cost: "1500000",
              currency: "сум",
            },
          ],
        ],
        [
          "Аксессуары",
          [
            {
              name: "RAM 8gb 3200hz для ПК от HYPERX с радиато",
              link: "/",
              img: 1,
              rating: 4.95,
              sale: 0,
              xit: true,
              review: 31,
              typeOfMoney: "В наличии",
              cost: "1500000",
              currency: "сум",
            },
            {
              name: "RAM 8gb 3200hz для ПК от HYPERX с радиато",
              link: "/",
              img: 2,
              rating: 4.95,
              sale: 0,
              xit: true,
              review: 31,
              typeOfMoney: "В наличии",
              cost: "1500000",
              currency: "сум",
            },
            {
              name: "RAM 8gb 3200hz для ПК от HYPERX с радиато",
              link: "/",
              img: 3,
              rating: 4.95,
              sale: 0,
              xit: true,
              review: 31,
              typeOfMoney: "В наличии",
              cost: "1500000",
              currency: "сум",
            },
            {
              name: "RAM 8gb 3200hz для ПК от HYPERX с радиато",
              link: "/",
              img: 1,
              rating: 4.95,
              sale: 0,
              xit: true,
              review: 31,
              typeOfMoney: "В наличии",
              cost: "1500000",
              currency: "сум",
            },
            {
              name: "RAM 8gb 3200hz для ПК от HYPERX с радиато",
              link: "/",
              img: 2,
              rating: 4.95,
              sale: 0,
              xit: true,
              review: 31,
              typeOfMoney: "В наличии",
              cost: "1500000",
              currency: "сум",
            },
            {
              name: "RAM 8gb 3200hz для ПК от HYPERX с радиато",
              link: "/",
              img: 3,
              rating: 4.95,
              sale: 0,
              xit: true,
              review: 31,
              typeOfMoney: "В наличии",
              cost: "1500000",
              currency: "сум",
            },
            {
              name: "RAM 8gb 3200hz для ПК от HYPERX с радиато",
              link: "/",
              img: 1,
              rating: 4.95,
              sale: 0,
              xit: true,
              review: 31,
              typeOfMoney: "В наличии",
              cost: "1500000",
              currency: "сум",
            },
            {
              name: "RAM 8gb 3200hz для ПК от HYPERX с радиато",
              link: "/",
              img: 2,
              rating: 4.95,
              sale: 0,
              xit: true,
              review: 31,
              typeOfMoney: "В наличии",
              cost: "1500000",
              currency: "сум",
            },
            {
              name: "RAM 8gb 3200hz для ПК от HYPERX с радиато",
              link: "/",
              img: 3,
              rating: 4.95,
              sale: 0,
              xit: true,
              review: 31,
              typeOfMoney: "В наличии",
              cost: "1500000",
              currency: "сум",
            },
          ],
        ],
      ],
    };
  },
});
